1. What does Pandas stand for?

An open source python package that is most widely used for data science/data analysis and machine learning tasks.

2. What are the 2 collections used in Pandas?

Series, Dataframe

3. Name 4 things Pandas can do for us.

Data cleansing,Data normalization,Data visualization,Data inspection

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

The keyword inplace which will modify the underlying data if set to true.

5. What is a CSV

A comma-separated values file is a delimited text file that uses a comma to separate values

6. When cleaning data what values do we not like in our data?

Null values are not liked as well as incorrect data which could be a string in a integer column.

In [17]:
#7.Importing numpy and using the reshape method
import numpy as np
array = np.arange(12).reshape((2,3,2))
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [72]:
#8Using linspace() in numpy
import numpy as np
array_line = np.linspace(0,20,num = 6)
print("The result os linspace():",array_line)

The result os linspace(): [ 0.  4.  8. 12. 16. 20.]


In [76]:
#9 Ussing deepcopy() function
import copy

array_copy =  copy.deepcopy(array_line)
print("The result after deepcopy function:",array_copy)

The result after deepcopy function: [ 0.  4.  8. 12. 16. 20.]


In [81]:
#11 concatenate these 3 arrays into a new array
import numpy as np
array_1 = ([[25, 16]])
array_2 = ([[11, 2], [13, 4]])
array_3 = ([[7, 81], [5, 6], [11, 12]])

#concatenating 3 arrays into new array
newArray = np.concatenate((array_1,array_2,array_3))
print("The new array:\n", newArray)

The new array:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [86]:
#12 sorted sarray
#Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)
print("Sorted array:\n",sortedArray)



Sorted array:
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [87]:
#13 Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
reshapedArray = sortedArray.reshape(2,2,3)
print("Reshaped array:\n",reshapedArray)

Reshaped array:
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]


In [100]:
#14 Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
a,b = reshapedArray
unpack1,unpack2 = a
unpack3,unpack4 = b
print("unpack1 array is:", unpack1)
print("unpack2 array is:", unpack2)
print("unpack3 array is:", unpack3)
print("unpack4 array is:", unpack4)



unpack1 array is: [16 25  2]
unpack2 array is: [11  4 13]
unpack3 array is: [ 7 81  5]
unpack4 array is: [ 6 11 12]


In [9]:
#15 Combined and sort the following arrays into one called 'comboArray' ...
import numpy as np
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
#concatenate 3 arrays into one array
four = np.concatenate((one,two,three))
#combo array
comboArray = np.sort(four)
print("combined array:\n",comboArray)


#16 Take 'comboArray' and perform the following slicing activities:
#print sec1 - the 2nd element
print("sec1:",comboArray[1])
#print sec2 - all elements from the 3rd element to the last
print("sec2:",comboArray[2:])
#print sec3 - all elements from the 4th to the 14th elements
print("sec3:",comboArray[3:14])
#print sec4 - the last 6 elements
print("sec4:",comboArray[-6:])
#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print("sec5:",comboArray[-28:-10])
#print sec6 - from #20 every even element to the end
print("sec6:",np.arange(comboArray[16],comboArray[23],2))
#print sec7 - from the last element moving forward, every 5th element.
print("Sec7:",np.arange(comboArray[-1],comboArray[-24],-5))

combined array:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6: [20 22 24 26]
Sec7: [27 22 17 12  7  2]


In [10]:
#20 Using `Series`, create a `DataFrame` that looks like this:
import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name = "Ingredients")
Quantity = pd.Series([4, 1, 2, 1], name = "Quantity")
Unit = pd.Series(["cups", "cup", "large","can"], name = "Unit")

shoppinglist_DF = pd.concat([Ingredients, Quantity, Unit], axis = 1)
print(shoppinglist_DF)
print(shoppinglist_DF.loc[2])



  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can
Ingredients     Eggs
Quantity           2
Unit           large
Name: 2, dtype: object


In [11]:
#21 Take this data and create a DataFrame named studentData

students = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
studentData = pd.DataFrame(students)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [12]:
#22 Add a new column to the DataFrame with the following deserts:
#        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData = studentData.assign(deserts = deserts)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [13]:
#23 Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ["Name","address"], inplace = True)
print("sorted DF\n", studentData)

sorted DF
       Name  Height Qualification  address  Age        Pets           sport   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [14]:
#24 Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:
import pandas as pd
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year1', 'Year2'])
df.to_csv("cows_and_goats.csv",index = False)
df

Cows  Goats
Year1    12     22
Year2    20     19

In [15]:
#25 (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
import pandas as pd
veggies = {
    "Name": ["Brinjal","Lady finger","potato","Cauliflower"],
    "Favorite": ["yes","yes","yes","no"],
}
veggiesDF = pd.DataFrame(veggies)
print("veggies list: \n",veggiesDF)
# Save veggie dataframe to CSV
veggiesDF.to_csv("Veggies_list.csv",index=False)

#using pandas make a change to your csv file and sav a copy with different name
new_veggie_list = pd.read_csv("Veggies_list.csv")
green_leafs = ["spinach","bressel sprouts","celery","kale"]
    
new_veggie_list["green_leafs"] = green_leafs
#save new veggies list to new csv file
new_veggie_list.to_csv("new_veggie_list.csv",index=False)
print("new veggie list:\n ", new_veggie_list)


veggies list: 
           Name Favorite
0      Brinjal      yes
1  Lady finger      yes
2       potato      yes
3  Cauliflower       no
new veggie list:
            Name Favorite      green_leafs
0      Brinjal      yes          spinach
1  Lady finger      yes  bressel sprouts
2       potato      yes           celery
3  Cauliflower       no             kale
